### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by gajet5** [msathis/node-http-ntlm#1]
```
C:\Users\Zadonsky.KL\Documents\Bot-SCV-v3\node_modules\request-simple-ntlm\lib\ntlm.js:106
		return callback(new Error("Couldn't find NTLM in the message type2 comming from the server"));
		       ^

TypeError: callback is not a function
    at Object.parseType2Message (C:\Users\Zadonsky.KL\Documents\Bot-SCV-v3\node_modules\request-simple-ntlm\lib\ntlm.js:106:10)
    at C:\Users\Zadonsky.KL\Documents\Bot-SCV-v3\node_modules\request-simple-ntlm\index.js:48:24
    at fn (C:\Users\Zadonsky.KL\Documents\Bot-SCV-v3\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (C:\Users\Zadonsky.KL\Documents\Bot-SCV-v3\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

mb fix: https://github.com/amirgon/node-http-ntlm/commit/31b25439ebdd97aadafb355b8febba866e5c8bb1

**Comment by ultimate-tester** [comment]
This was fixed in the latest commit. You can safely close this issue.
